language: php

php:
    - 7.3
    - 7.4
    - nightly

env:
    global:
        - CHECK_PHP_SYNTAX="no"

matrix:
    include:
        php: 7.4
        env: CHECK_PHP_SYNTAX="yes"

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then composer require --dev --no-update friendsofphp/php-cs-fixer; fi;
    - composer update --prefer-dist --no-interaction --no-suggest --no-progress --ansi

script:
    - if [[ "$CHECK_PHP_SYNTAX" == "no" ]]; then ./vendor/bin/phpunit; fi;
    - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then ./vendor/bin/php-cs-fixer fix --dry-run --diff --no-interaction -v; fi;
